---
name: Get Images for Build
description: Get Images for Build
inputs:
  image_flavor:
    description: "Types of Image to Build (Bazzite, Bluefin, Aurora)"
    required: true
outputs:
  images:
    description: "List of Images that will be built"
    value: ${{ steps.images.outputs.images }}
runs:
  using: "composite"
  steps:
    - name: Get Images for Build
      id: images
      shell: bash
      run: |-
        # Array to Hold Image Names
        images=()

        # Add Images
        case "${{ inputs.image_flavor }}" in
        "Bazzite")
          images+=("bazzite" "bazzite-deck" "bazzite-nvidia")
          images+=("bazzite-gnome" "bazzite-deck-gnome" "bazzite-gnome-nvidia")
          ;;
        "Bluefin")
          images+=("bluefin" "bluefin-nvidia")
          ;;
        "Aurora")
          images+=("aurora" "aurora-nvidia")
          ;;
        esac

        # Make into Json Array
        images="$(jq --null-input --compact-output '$ARGS.positional' \
        --args "${images[@]}")"

        # Output
        echo "images=$images" >> "$GITHUB_OUTPUT"
